2020-01-29 21:55:50.007629: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 FMA
2020-01-29 21:55:52.133025: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1432] Found device 0 with properties: 
name: Tesla P100-PCIE-16GB major: 6 minor: 0 memoryClockRate(GHz): 1.3285
pciBusID: 0000:88:00.0
totalMemory: 15.89GiB freeMemory: 15.60GiB
2020-01-29 21:55:52.133093: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1511] Adding visible gpu devices: 0
2020-01-29 21:55:52.544827: I tensorflow/core/common_runtime/gpu/gpu_device.cc:982] Device interconnect StreamExecutor with strength 1 edge matrix:
2020-01-29 21:55:52.544898: I tensorflow/core/common_runtime/gpu/gpu_device.cc:988]      0 
2020-01-29 21:55:52.544912: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1001] 0:   N 
2020-01-29 21:55:52.545371: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1115] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 15117 MB memory) -> physical GPU (device: 0, name: Tesla P100-PCIE-16GB, pci bus id: 0000:88:00.0, compute capability: 6.0)
/array/ssd/msmajdi/anaconda3/envs/new-env-fb2/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:523: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/array/ssd/msmajdi/anaconda3/envs/new-env-fb2/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:524: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/array/ssd/msmajdi/anaconda3/envs/new-env-fb2/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:525: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/array/ssd/msmajdi/anaconda3/envs/new-env-fb2/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:526: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
/array/ssd/msmajdi/anaconda3/envs/new-env-fb2/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:527: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
/array/ssd/msmajdi/anaconda3/envs/new-env-fb2/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:532: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])
Using TensorFlow backend.
/array/ssd/msmajdi/anaconda3/envs/new-env-fb2/lib/python3.6/site-packages/sklearn/externals/joblib/__init__.py:15: DeprecationWarning: sklearn.externals.joblib is deprecated in 0.21 and will be removed in 0.23. Please import this functionality directly from joblib, which can be installed with: pip install joblib. If this warning is raised when loading pickled models, you may need to re-serialize those models with scikit-learn 0.21+.
  warnings.warn(msg, category=DeprecationWarning)
Loading test:   0%|          | 0/4 [00:00<?, ?it/s]Loading test:  25%|██▌       | 1/4 [00:04<00:12,  4.05s/it]Loading test:  50%|█████     | 2/4 [00:07<00:07,  3.94s/it]Loading test:  75%|███████▌  | 3/4 [00:11<00:03,  3.93s/it]Loading test: 100%|██████████| 4/4 [00:21<00:00,  5.57s/it]Loading test: 100%|██████████| 4/4 [00:21<00:00,  5.26s/it]
concatenating: validation:   0%|          | 0/4 [00:00<?, ?it/s]concatenating: validation:  25%|██▌       | 1/4 [00:00<00:01,  1.90it/s]concatenating: validation:  50%|█████     | 2/4 [00:01<00:01,  1.92it/s]concatenating: validation:  75%|███████▌  | 3/4 [00:01<00:00,  1.94it/s]concatenating: validation: 100%|██████████| 4/4 [00:02<00:00,  1.95it/s]concatenating: validation: 100%|██████████| 4/4 [00:02<00:00,  1.96it/s]
Loading testS:   0%|          | 0/4 [00:00<?, ?it/s]Loading testS:  25%|██▌       | 1/4 [00:43<02:11, 43.83s/it]----------+++ 
CrossVal ['a']
CrossVal ['a']
(0/4) test vimp2_A_CSFn2
(1/4) test vimp2_ANON967_CSFn2
(2/4) test vimp2_B_CSFn2
(3/4) test vimp2_E_CSFn2
---
---
---------------------- check Layers Step ------------------------------
 N: [1]  | GPU: 6  | SD 2  | Dropout 0.5  | LR 0.001  | NL 3  |  Cascade |  FM 20 |  Upsample 1

 #layer 3 #layers changed False
---------------------------------------------------------------
 Nucleus: [1]  | GPU: 6  | SD 2  | Dropout 0.5  | LR 0.001  | NL 3  |  Cascade |  FM 20 |  Upsample 1
Experiment: exp6_uncropped
SubExperiment: sE12_Cascade_FM20_Res_Unet2_NL3_LS_MyDice_US1_wLRScheduler_lr0.001_CSFn2_Init_Main_WITH_NEW_CASES_wBiasCorrection_CV_a
---------------------------------------------------------------
---
---
Traceback (most recent call last):
  File "/array/ssd/msmajdi/anaconda3/envs/new-env-fb2/lib/python3.6/site-packages/nibabel/loadsave.py", line 40, in load
    stat_result = os.stat(filename)
FileNotFoundError: [Errno 2] No such file or directory: '/array/ssd/msmajdi/experiments/keras/exp6_uncropped/crossVal/CSFn2/a/vimp2_ANON967_CSFn2/PProcessed.nii.gz'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 1960, in <module>
    Run_Csfn_with_Best_WMn_architecture(UserInfoB)
  File "main.py", line 1949, in Run_Csfn_with_Best_WMn_architecture
    Run(UserInfoB, IV)    
  File "main.py", line 231, in Run
    else: Loop_Over_Nuclei(UserInfoB)
  File "main.py", line 104, in Loop_Over_Nuclei
    Run_Main(UserI)
  File "main.py", line 225, in Run_Main
    Loop_slicing_orientations(UserInfoB, InitValues)
  File "main.py", line 223, in Loop_slicing_orientations
    subRun(UserInfoB)
  File "main.py", line 217, in subRun
    else: normal_run(params)
  File "main.py", line 203, in normal_run
    Data, params = datasets.loadDataset(params)                             
  File "/array/ssd/msmajdi/code/thalamus/keras/otherFuncs/datasets.py", line 411, in loadDataset
    Data = main_ReadingDataset(params)
  File "/array/ssd/msmajdi/code/thalamus/keras/otherFuncs/datasets.py", line 403, in main_ReadingDataset
    DataAll.Sagittal_Test          = readingAllSubjects(params.directories.Test.Input_Sagittal.Subjects , 'testS' )               
  File "/array/ssd/msmajdi/code/thalamus/keras/otherFuncs/datasets.py", line 355, in readingAllSubjects
    im, imF = readingImage(params, subject, mode)
  File "/array/ssd/msmajdi/code/thalamus/keras/otherFuncs/datasets.py", line 171, in readingImage
    imF, im = readingWithTranpose(subject2.address + '/' + subject2.ImageProcessed + '.nii.gz' , params)
  File "/array/ssd/msmajdi/code/thalamus/keras/otherFuncs/datasets.py", line 121, in readingWithTranpose
    ImageF, Image = read_cropped_inputs(params, subject2, Dirr)
  File "/array/ssd/msmajdi/code/thalamus/keras/otherFuncs/datasets.py", line 106, in read_cropped_inputs
    inputF = nib.load(dirrectory)
  File "/array/ssd/msmajdi/anaconda3/envs/new-env-fb2/lib/python3.6/site-packages/nibabel/loadsave.py", line 42, in load
    raise FileNotFoundError("No such file or no access: '%s'" % filename)
FileNotFoundError: No such file or no access: '/array/ssd/msmajdi/experiments/keras/exp6_uncropped/crossVal/CSFn2/a/vimp2_ANON967_CSFn2/PProcessed.nii.gz'
Loading testS:  25%|██▌       | 1/4 [00:43<02:11, 43.83s/it]
